import './globals.css'; // Import global styles
import { ThemeProvider } from './theme/ThemeContext'; // Import ThemeProvider
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ThemeWrapper from './theme/ThemeWrapper'; // Import ThemeWrapper

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <ThemeWrapper>
            {children}
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
